# Generated by Django 2.2.13 on 2022-05-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
